[project]
name = "rag-qae-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.110",
    "httpx>=0.28.1",
    "openai>=2.43.0",
    "pgvector>=0.4.2",
    "pydantic>=2",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.29",
]
